### ISSUE TITLE
Create a data transformer for IoCDumper.java

### ISSUE THREAD

**Issue by Karm** [Karm/ispn-dump2proto#2]
* When it is necessary to change the data for all the records
* One needs to dump the cache, modify the data, re-upload (push)
* The task is infrequent, yet immensely tedious if executed manually

**Comment by Karm** [comment]
So far we have to address:
```
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.presentOnWhiteList was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.blackListedDomainOrIP was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.presentOnWhiteList was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.blackListedDomainOrIP was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.presentOnWhiteList was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.blackListedDomainOrIP was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.presentOnWhiteList was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.blackListedDomainOrIP was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.presentOnWhiteList was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.blackListedDomainOrIP was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.presentOnWhiteList was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.blackListedDomainOrIP was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.presentOnWhiteList was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.blackListedDomainOrIP was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
WARN: PROTOSTREAM000001: Field sinkitprotobuf.BlacklistedRecordList.BlacklistedRecord.crc64Hash was read out of sequence leading to sub-optimal performance
Jul 12, 2018 11:25:47 PM org.infinispan.protostream.impl.ProtoStreamReaderImpl checkFieldRead
```

**Comment by Karm** [comment]
And the infamous:
```
protostream.com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
        at protostream.com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:110)
        at protostream.com.google.protobuf.CodedInputStream.tryRefillBuffer(CodedInputStream.java:1131)
        at protostream.com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1081)
        at protostream.com.google.protobuf.CodedInputStream.ensureAvailable(CodedInputStream.java:1068)
        at protostream.com.google.protobuf.CodedInputStream.readRawBytesSlowPath(CodedInputStream.java:1203)
        at protostream.com.google.protobuf.CodedInputStream.readByteArray(CodedInputStream.java:533)
        at org.infinispan.protostream.impl.RawProtoStreamReaderImpl.readByteArray(RawProtoStreamReaderImpl.java:112)
        at org.infinispan.protostream.impl.UnknownFieldSetImpl.readSingleField(UnknownFieldSetImpl.java:80)
        at org.infinispan.protostream.impl.ProtoStreamReaderImpl.readCollection(ProtoStreamReaderImpl.java:310)
        at biz.karms.protostream.ioc.marshallers.BlacklistedRecordMarshaller.readFrom(BlacklistedRecordMarshaller.java:38)
        at biz.karms.protostream.ioc.marshallers.BlacklistedRecordMarshaller.readFrom(BlacklistedRecordMarshaller.java:22)
        at org.infinispan.protostream.impl.MessageMarshallerDelegate.unmarshall(MessageMarshallerDelegate.java:113)
        at org.infinispan.protostream.impl.ProtoStreamReaderImpl.readNestedObject(ProtoStreamReaderImpl.java:270)
        at org.infinispan.protostream.impl.ProtoStreamReaderImpl.readCollection(ProtoStreamReaderImpl.java:308)
        at biz.karms.protostream.ioc.marshallers.BlacklistedRecordListMarshaller.readFrom(BlacklistedRecordListMarshaller.java:26)
        at biz.karms.protostream.ioc.marshallers.BlacklistedRecordListMarshaller.readFrom(BlacklistedRecordListMarshaller.java:12)
        at org.infinispan.protostream.impl.MessageMarshallerDelegate.unmarshall(MessageMarshallerDelegate.java:113)
        at org.infinispan.protostream.ProtobufUtil.readFrom(ProtobufUtil.java:68)
        at org.infinispan.protostream.ProtobufUtil.readFrom(ProtobufUtil.java:72)
        at biz.karms.CacheUploader.upload(CacheUploader.java:85)
        at biz.karms.CacheUploader.main(CacheUploader.java:118)
```

My modified version of protostream-agregator has
```
      codedInputStream.setSizeLimit(268435456);
```
Which is not enough for ~500M file :small_airplane:  
TODO: Shouldn't it be possible to move pointer by offset in the file instead deserializing the whole list an block?
TODO: Make the attrbute configurable and open PR to https://github.com/infinispan/protostream
